version: '3.8'

services:
  app:
    image: giatrong/quizrise-be   # lấy image từ Docker Hub -> ko cần build lại lần nữa
    container_name: quizrise-be
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env  
    ports:
      - "3000:3000" 
    networks:
      - quizrise-net

  mongodb:
    image: mongo:7
    container_name: quizrise-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db
    networks:
      - quizrise-net

volumes:
  mongo-data:
    driver: local

networks:
  quizrise-net:
    driver: bridge