name: Quizrise Backend CI/CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]        # chạy khi push vào nhánh main hoặc dev
  pull_request:
    branches: [ "main", "dev" ]
name: CI/CD Pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build & push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: giatrong/quizlet

      # # 4. Deploy trên Linux server qua SSH
      # - name: Deploy to Linux server
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd ~/quizlet
      #       docker compose -f docker-compose-uat.yaml --env-file .env.uat pull
      #       docker compose -f docker-compose-uat.yaml --env-file .env.uat up -d